config/routes.rb
Rails.application.routes.draw do
  resources :degrees
  resources :universities
  resources :applicants

  root "applicants#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/degree.rb
class Degree < ApplicationRecord
end

app/models/university.rb
class University < ApplicationRecord
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:name, :email, :phone, :university, :major, :graduation_time, :sponsorship, :degree)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:degree)
    end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:name)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/applicants/_form.html.erb
<%= semantic_form_for @applicant do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :university %>
    <%= f.input :major %>
    <%= f.input :graduation_time %>
    <%= f.input :sponsorship %>
    <%= f.input :degree %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applicants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>University</th>
      <th>Major</th>
      <th>Graduation time</th>
      <th>Sponsorship</th>
      <th>Degree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= applicant.name %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.phone %></td>
        <td><%= applicant.university %></td>
        <td><%= applicant.major %></td>
        <td><%= applicant.graduation_time %></td>
        <td><%= applicant.sponsorship %></td>
        <td><%= applicant.degree %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>Start your job applicaiton</h1>

<%= semantic_form_for @applicant do |f| %>
  <%= f.inputs "Contact Information", :id => "basic" do %>
    <%= f.input :name, :input_html => { :size => 20 } %>
    <%= f.input :email, :input_html => { :size => 20 } %>
    <%= f.input :phone, :input_html => { :size => 20 } %>
  <% end %>
  <%= f.inputs :name => "Education Background", :id => "advanced" do %>
      <%= f.input :university, :as => :select, :collection => University.pluck(:name) %>
      <%= f.input :major %>
      <%= f.input :graduation_time, :label => "Intended graduation date", :as => :date_select%>
      <%= f.input :sponsorship, :label => "Do you need sponsorship?",:as => :radio %>
      <%= f.input :degree, :as => :select, :collection => Degree.pluck(:degree) %>
      <%= f.input :resume, :input_html => { :class => 'autogrow', :rows => 10, :cols => 100, :maxlength => 100  } %>
    <% end %>
  <%= f.actions do %>
      <%= f.action :submit, :as => :button, :label => "Submit"%>
      <%= f.action :cancel, :as => :link, :label => "Cancel your application" %>
  <% end %>
<% end %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applicant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @applicant.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @applicant.phone %>
</p>

<p>
  <strong>University:</strong>
  <%= @applicant.university %>
</p>

<p>
  <strong>Major:</strong>
  <%= @applicant.major %>
</p>

<p>
  <strong>Graduation time:</strong>
  <%= @applicant.graduation_time %>
</p>

<p>
  <strong>Sponsorship:</strong>
  <%= @applicant.sponsorship %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @applicant.degree %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

app/views/degrees/_form.html.erb
<%= semantic_form_for @degree do |f| %>
  <%= f.inputs do %>
    <%= f.input :degree %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= degree.degree %></td>
        <td><%= link_to 'Show', degree %></td>
        <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
        <td><%= link_to 'Destroy', degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @degree.degree %>
</p>

<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormtasticApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
    <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/universities/_form.html.erb
<%= semantic_form_for @university do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.name %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>